### ISSUE TITLE
support for DBwithTTL

### ISSUE THREAD

**Issue by brigadier** [barrel-db/barrel_rocksdb#2]
How hard would it be to add support for DBWithTTL? Am I right that almost every part of code must be duplicated as casts are impossible because there's no inheritance relationship between DB and DBWithTTL but composition?

**Comment by benoitc** [comment]
@brigadier why not doing over the primitive like it is done in C. As far as I understand a db with TTL is using a specific column family. 

I think what we really miss is the possibility to create a custom merge function of compaction right now. Not sure what's the best way to handle it right now.

**Comment by benoitc** [comment]
closing the issue. code have been moved to gitlab: https://gitlab.com/barreldb-archive/barrel_rocksdb
