### ISSUE TITLE
freebsd compile error

### ISSUE THREAD

**Issue by stofel** [barrel-db/barrel_rocksdb#3]
Cant compile it on freebsd with gcc48 nor gcc49

**Comment by benoitc** [comment]
@stofel can you give me the full error?

**Comment by benoitc** [comment]
@lso which version of freebsd are you using?

**Comment by stofel** [comment]
uname -a
FreeBSD devel 10.2-RELEASE-p9 FreeBSD 10.2-RELEASE-p9 #0: Thu Jan 14
01:32:46 UTC 2016
root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
amd64

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc48/gcc/x86_64-portbld-freebsd10.2/4.8.5/lto-wrapper
Target: x86_64-portbld-freebsd10.2
Configured with: ./../gcc-4.8.5/configure --disable-multilib
--disable-bootstrap --disable-nls --enable-gnu-indirect-function
--libdir=/usr/local/lib/gcc48 --libexecdir=/usr/local/libexec/gcc48
--program-suffix=48 --with-as=/usr/local/bin/as --with-gmp=/usr/local
--with-gxx-include-dir=/usr/local/lib/gcc48/include/c++/
--with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection'
--with-system-zlib --with-ecj-jar=/usr/local/share/java/ecj-4.5.jar
--enable-languages=c,c++,objc,fortran,java --prefix=/usr/local
--localstatedir=/var --mandir=/usr/local/man
--infodir=/usr/local/info/gcc48 --build=x86_64-portbld-freebsd10.2
Thread model: posix
gcc version 4.8.5 (FreeBSD Ports Collection)



]>./rebar3 compile
...
  GEN      util/build_version.cc
  GEN      util/build_version.cc
  CC       db/auto_roll_logger.o
  CC       db/builder.o
  CC       db/c.o
  CC       db/column_family.o
  CC       db/compacted_db_impl.o
  CC       db/compaction.o
  CC       db/compaction_iterator.o
  CC       db/compaction_job.o
In file included from db/compaction_job.cc:59:0:
./util/string_util.h: In function 'std::string rocksdb::ToString(T)':
./util/string_util.h:20:10: error: 'to_string' is not a member of 'std'
   return std::to_string(value);
          ^
./util/string_util.h: In function 'std::string rocksdb::ToString(T) [with T
= int; std::string = std::basic_string<char>]':
./util/string_util.h:28:1: warning: control reaches end of non-void
function [-Wreturn-type]
 }
 ^
gmake: *** [Makefile:1390: db/compaction_job.o] Error 1
===> Hook for compile failed!



2016-08-16 13:24 GMT+04:00 Benoit Chesneau <notifications@github.com>:

**Comment by benoitc** [comment]
thanks, i will try later today in a vagrant box

**Comment by benoitc** [comment]
@stofel the following diff fix the compilation:

```diff
[vagrant@ ~/barrel_rocksdb]$ git diff --color | less -r
diff --git a/c_src/build_deps.sh b/c_src/build_deps.sh
index 53c0232..33a71ac 100755
--- a/c_src/build_deps.sh
+++ b/c_src/build_deps.sh
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/local/bin/bash

 # /bin/sh on Solaris is not a POSIX compatible shell, but /usr/bin/ksh is.
 if [ `uname -s` = 'SunOS' -a "${POSIX_SHELL}" != "true" ]; then
@@ -76,8 +76,8 @@ case "$1" in
             (cd snappy-$SNAPPY_VSN && $MAKE && $MAKE install)
         fi

-        export CFLAGS="$CFLAGS -I $BASEDIR/system/include"
-        export CXXFLAGS="$CXXFLAGS -I $BASEDIR/system/include"
+        export CFLAGS="$CFLAGS -D_GLIBCXX_USE_C99 -I $BASEDIR/system/include"
+        export CXXFLAGS="$CXXFLAGS -D_GLIBCXX_USE_C99 -I $BASEDIR/system/include"
         export LDFLAGS="$LDFLAGS -L$BASEDIR/system/lib"
         export LD_LIBRARY_PATH="$BASEDIR/system/lib:$LD_LIBRARY_PATH"
```

I need to find a correct way to add this change depending on the platform. Also makes sure to use a version of Erlang compiled with the dirty nifs schedulers.

**Comment by stofel** [comment]
With 
`-        export CFLAGS="$CFLAGS -I $BASEDIR/system/include"
-        export CXXFLAGS="$CXXFLAGS -I $BASEDIR/system/include"
+        export CFLAGS="$CFLAGS -D_GLIBCXX_USE_C99 -I $BASEDIR/system/include"
+        export CXXFLAGS="$CXXFLAGS -D_GLIBCXX_USE_C99 -I $BASEDIR/system/include"`
It is compiling as standalone.
I thing change `#!/bin/sh` to `#!/usr/local/bin/bash` bad idea, bash not part of freebsd and can be not installed.

As dependency in rebar3 project get some conflict with application name erocksdb.
For example as _checkout/barrel_rocksdb get:
`===> Compiling ibrowse
===> Compiling erocksdb
/usr/home/work/ecolor/_build/default/lib/erocksdb/src/erocksdb.erl:103: Warning: record cf_descriptor is un
used

===> Linking /usr/home/work/ecolor/_build/default/lib/erocksdb/priv/erocksdb.so
*** Error code 1

Stop.
make: stopped in /usr/home/work/ecolor
`

**Comment by stofel** [comment]
Compiling is ok, but priv/erocksdb.so not exists
]>./rebar3 compile
===> Compiling /usr/alexs/work/barrel_rocksdb/c_src/util.cc
===> Linking /usr/home/work/barrel_rocksdb/priv/erocksdb.so
]>ls priv/
]>
`

**Comment by benoitc** [comment]
Did yoy get such errors:

```
/home/vagrant/barrel_rocksdb/c_src/erocksdb.cc:90:56: error: use of undeclared identifier 'ERL_NIF_DIRTY_JOB_CPU_BOUND'
    {"release_snapshot", 1, erocksdb::ReleaseSnapshot, ERL_NIF_DIRTY_JOB_CPU_BOUND},
                                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

?

**Comment by stofel** [comment]
Yes. But after recompiling my erlang to with dirty nif shedulers support, that errors gone

**Comment by benoitc** [comment]
OK, i'm launching a new build to test.

**Comment by stofel** [comment]
Possible it is not barrel_rocksdb issue. 
I try build https://github.com/facebook/rocksdb its fails with like same errors
~/rocksdb]>gmake
...
  CC       util/lru_cache.o
  CC       util/threadpool.o
  CC       util/transaction_test_util.o
util/transaction_test_util.cc: In member function 'bool rocksdb::RandomTransactionInserter::DoInsert(rocksdb::DB*, rocksdb::Transaction*, bool)':
util/transaction_test_util.cc:97:19: error: 'stoull' is not a member of 'std'
       int_value = std::stoull(value);
                   ^
util/transaction_test_util.cc: In static member function 'static rocksdb::Status rocksdb::RandomTransactionInserter::Verify(rocksdb::DB*, uint16_t)':
util/transaction_test_util.cc:208:28: error: 'stoull' is not a member of 'std'
       uint64_t int_value = std::stoull(value.ToString());
                            ^
gmake: *** [Makefile:1456: util/transaction_test_util.o]  error 1

**Comment by benoitc** [comment]
closing the issue. code have been moved to gitlab: https://gitlab.com/barreldb-archive/barrel_rocksdb
